export const INDIAN_INDICES = [
  { symbol: "^NSEI", name: "NIFTY 50" },
  { symbol: "^BSESN", name: "S&P BSE SENSEX" },
  { symbol: "^NSEBANK", name: "NIFTY BANK" },
  { symbol: "^CNXIT", name: "NIFTY IT" },
  { symbol: "^CNXAUTO", name: "NIFTY AUTO" },
  { symbol: "^CNXPHARMA", name: "NIFTY PHARMA" },
  { symbol: "^CNXMETAL", name: "NIFTY METAL" },
  { symbol: "^CNXFMCG", name: "NIFTY FMCG" },
  { symbol: "^CNXMEDIA", name: "NIFTY MEDIA" },
  { symbol: "^CNXENERGY", name: "NIFTY ENERGY" },
  { symbol: "^CNXINFRA", name: "NIFTY INFRA" },
  { symbol: "^CNXREALTY", name: "NIFTY REALTY" },
  { symbol: "^CNXPSUBANK", name: "NIFTY PSU BANK" },
  { symbol: "^CNXSERVICE", name: "NIFTY SERVICES" },
];

export const POPULAR_INDIAN_STOCKS = [
  ...INDIAN_INDICES,
  { symbol: "RELIANCE.NS", name: "Reliance Industries Limited" },
  { symbol: "TCS.NS", name: "Tata Consultancy Services Limited" },
  { symbol: "HDFCBANK.NS", name: "HDFC Bank Limited" },
  { symbol: "ICICIBANK.NS", name: "ICICI Bank Limited" },
  { symbol: "INFY.NS", name: "Infosys Limited" },
  { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever Limited" },
  { symbol: "ITC.NS", name: "ITC Limited" },
  { symbol: "SBIN.NS", name: "State Bank of India" },
  { symbol: "BHARTIARTL.NS", name: "Bharti Airtel Limited" },
  { symbol: "BAJFINANCE.NS", name: "Bajaj Finance Limited" },
  { symbol: "LTIM.NS", name: "LTIMindtree Limited" },
  { symbol: "MARUTI.NS", name: "Maruti Suzuki India Limited" },
  { symbol: "KOTAKBANK.NS", name: "Kotak Mahindra Bank Limited" },
  { symbol: "LT.NS", name: "Larsen & Toubro Limited" },
  { symbol: "AXISBANK.NS", name: "Axis Bank Limited" },
  { symbol: "ASIANPAINT.NS", name: "Asian Paints Limited" },
  { symbol: "ADANIENT.NS", name: "Adani Enterprises Limited" },
  { symbol: "SUNPHARMA.NS", name: "Sun Pharmaceutical Industries Limited" },
  { symbol: "TITAN.NS", name: "Titan Company Limited" },
  { symbol: "ULTRACEMCO.NS", name: "UltraTech Cement Limited" },
  { symbol: "WIPRO.NS", name: "Wipro Limited" },
  { symbol: "HCLTECH.NS", name: "HCL Technologies Limited" },
  { symbol: "NTPC.NS", name: "NTPC Limited" },
  { symbol: "M&M.NS", name: "Mahindra & Mahindra Limited" },
  { symbol: "POWERGRID.NS", name: "Power Grid Corporation of India Limited" },
  { symbol: "TATAMOTORS.NS", name: "Tata Motors Limited" },
  { symbol: "JSWSTEEL.NS", name: "JSW Steel Limited" },
  { symbol: "ADANIPORTS.NS", name: "Adani Ports and Special Economic Zone Limited" },
  { symbol: "ONGC.NS", name: "Oil and Natural Gas Corporation Limited" },
  { symbol: "GRASIM.NS", name: "Grasim Industries Limited" },
  { symbol: "HINDALCO.NS", name: "Hindalco Industries Limited" },
  { symbol: "NESTLEIND.NS", name: "Nestle India Limited" },
  { symbol: "BAJAJFINSV.NS", name: "Bajaj Finserv Limited" },
  { symbol: "TECHM.NS", name: "Tech Mahindra Limited" },
  { symbol: "CIPLA.NS", name: "Cipla Limited" },
  { symbol: "EICHERMOT.NS", name: "Eicher Motors Limited" },
  { symbol: "DRREDDY.NS", name: "Dr. Reddy's Laboratories Limited" },
  { symbol: "BRITANNIA.NS", name: "Britannia Industries Limited" },
  { symbol: "BPCL.NS", name: "Bharat Petroleum Corporation Limited" },
  { symbol: "APOLLOHOSP.NS", name: "Apollo Hospitals Enterprise Limited" },
  { symbol: "DIVISLAB.NS", name: "Divi's Laboratories Limited" },
  { symbol: "COALINDIA.NS", name: "Coal India Limited" },
  { symbol: "UPL.NS", name: "UPL Limited" },
  { symbol: "BAJAJ-AUTO.NS", name: "Bajaj Auto Limited" },
  { symbol: "HEROMOTOCO.NS", name: "Hero MotoCorp Limited" },
  { symbol: "SBILIFE.NS", name: "SBI Life Insurance Company Limited" },
  { symbol: "HDFCLIFE.NS", name: "HDFC Life Insurance Company Limited" },
  { symbol: "TATACONSUM.NS", name: "Tata Consumer Products Limited" },
  { symbol: "INDUSINDBK.NS", name: "IndusInd Bank Limited" },
  { symbol: "RELIANCE.BO", name: "Reliance Industries Limited (BSE)" },
  { symbol: "TCS.BO", name: "Tata Consultancy Services Limited (BSE)" },
  { symbol: "HDFCBANK.BO", name: "HDFC Bank Limited (BSE)" },
  { symbol: "ZOMATO.NS", name: "Zomato Limited" },
  { symbol: "PAYTM.NS", name: "One 97 Communications Limited" },
  { symbol: "NYKAA.NS", name: "FSN E-Commerce Ventures Limited" },
  { symbol: "IRCTC.NS", name: "Indian Railway Catering and Tourism Corporation Limited" },
  { symbol: "HAL.NS", name: "Hindustan Aeronautics Limited" },
  { symbol: "BEL.NS", name: "Bharat Electronics Limited" },
  { symbol: "RVNL.NS", name: "Rail Vikas Nigam Limited" },
  { symbol: "IREDA.NS", name: "Indian Renewable Energy Development Agency Limited" },
  { symbol: "JIOFIN.NS", name: "Jio Financial Services Limited" },
  { symbol: "ADANIPOWER.NS", name: "Adani Power Limited" },
  { symbol: "ADANIGREEN.NS", name: "Adani Green Energy Limited" },
  { symbol: "ADANITRANS.NS", name: "Adani Energy Solutions Limited" },
  { symbol: "AWL.NS", name: "Adani Wilmar Limited" },
  { symbol: "YESBANK.NS", name: "Yes Bank Limited" },
  { symbol: "IDFCFIRSTB.NS", name: "IDFC First Bank Limited" },
  { symbol: "PNB.NS", name: "Punjab National Bank" },
  { symbol: "BANKBARODA.NS", name: "Bank of Baroda" },
  { symbol: "CANBK.NS", name: "Canara Bank" },
  { symbol: "UNIONBANK.NS", name: "Union Bank of India" },
  { symbol: "IOB.NS", name: "Indian Overseas Bank" },
  { symbol: "UCOBANK.NS", name: "UCO Bank" },
  { symbol: "CENTRALBK.NS", name: "Central Bank of India" },
  { symbol: "MAHABANK.NS", name: "Bank of Maharashtra" },
  { symbol: "PSB.NS", name: "Punjab & Sind Bank" },
  { symbol: "DLF.NS", name: "DLF Limited" },
  { symbol: "LODHA.NS", name: "Macrotech Developers Limited" },
  { symbol: "GODREJPROP.NS", name: "Godrej Properties Limited" },
  { symbol: "OBEROIRLTY.NS", name: "Oberoi Realty Limited" },
  { symbol: "PHOENIXLTD.NS", name: "The Phoenix Mills Limited" },
  { symbol: "PRESTIGE.NS", name: "Prestige Estates Projects Limited" },
  { symbol: "BRIGADE.NS", name: "Brigade Enterprises Limited" },
  { symbol: "SOBHA.NS", name: "Sobha Limited" },
  { symbol: "SUNTECK.NS", name: "Sunteck Realty Limited" },
];
